name : "practice-workflows"
on : 
    workflow_dispatch : 
        
jobs : 
    build : 
        runs-on : ubuntu-latest
        steps : 
            - name : "Checkout code"
              uses : actions/checkout@v4
            - name : "echo hi "
              run : echo "hi from Yajnesh "
